spring:
  redis:
    host: 192.168.211.131
    port: 6379
    password:
    timeout: 3600ms #超时时间
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接 默认8
        max-wait: -1ms #默认-1 最大连接阻塞等待时间
        min-idle: 0 #最小空闲连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tmall_ssm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 210666
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.redis.demo.damain
  mapper-locations: classpath:mapper/*Mapper.xml